version: "3.8"

services:
  app:
    build: .
    ports:
      - "4041:4041"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/devices

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: csvdb
    volumes:
      - /home/vishal/docker-volumes/db_data:/var/lib/postgresql/data  # Local system volume
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "4043:80"
    volumes:
      - /home/vishal/docker-volumes/pgadmin:/var/lib/pgadmin
      - /home/vishal/docker-volumes/pgadmin/sessions:/var/lib/pgadmin/sessions

volumes:
  db_data: {}

networks:
  app-network:
    driver: bridge