version: "3.8"

services:
  app:
    build: .
    ports:
      - "4041:4041"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/csvdb

    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "devices", "-h", "db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: csvdb
    volumes:
      - "/c/Users/thoratvishal.sanjay/Documents/docker-volumes/db_data:/var/lib/postgresql/data"
      - "./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh" # Mount initialization script
    ports:
      - "5433:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "4043:80"
    volumes:
      - "C:/Users/thoratvishal.sanjay/Documents/docker-volumes/pgadmin:/var/lib/pgadmin"
      - "C:/Users/thoratvishal.sanjay/Documents/docker-volumes/pgadmin/sessions:/var/lib/pgadmin/sessions"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: {}
